apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: preview-feature-demo-workflow

resources:
- ../../base

images:
- name: 10.108.98.54:80/java-app
  newTag: demo-workflow

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: feature-demo-workflow.local
  target:
    kind: Ingress
    name: auth-service

commonLabels:
  environment: preview
  branch: feature-demo-workflow
  managed-by: argocd

commonAnnotations:
  git-branch: "feature/demo-workflow"
  description: "Preview environment for demo-workflow"
