apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: preview-new-test

resources:
- ../../base

# Переопределение образа для feature ветки
images:
- name: java-app
  newName: java-app
  newTag: new-test

patches:
# Обновление host в Ingress
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: new-test.local
  target:
    kind: Ingress
    name: auth-service

# Обновление переменных окружения
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: "new-test"
  target:
    kind: Deployment
    name: auth-service

commonLabels:
  environment: preview
  branch: new-test
  managed-by: argocd
  feature: "true"

commonAnnotations:
  git-branch: "feature/new-test"
  description: "Preview environment for feature branch new-test"
  created-by: "argocd-applicationset"

